---
Double Rainbow:
- :title: Allegreto
  :artist: Bond
- :title: We Found Love (Rihanna Feat. Calvin Harris Remake)
  :artist: Cover Girl
- :title: Balancê
  :artist: Sara Tavares
- :title: /home/doug/Downloads/tapes/Double Rainbow/03 - Break_It_Down_[DIRTY].mp3
  :artist: Unknown
- :title: /home/doug/Downloads/tapes/Double Rainbow/10 - Nickel Creek - Nickel Creek
    - Lighthouse Tale.mp3
  :artist: Unknown
- :title: /home/doug/Downloads/tapes/Double Rainbow/08 - Of Monsters And Men - Of
    Monsters And Men - Little Talks.mp3
  :artist: Unknown
- :title: We Run The Night (Proper Villains Remix)
  :artist: Havana Brown Ft. Pitbull
- :title: Toes (Album Version)
  :artist: Zac Brown Band
- :title: Wild Ones (Flo Rida Feat. Sia Remake)
  :artist: Wild Flo
- :title: Till The World Ends (Alex Suarez Radio Remix)
  :artist: Britney Spears
- :title: Moves Like Jagger (Remix)
  :artist: Maroon 5
- :title: Take Care [Explicit]
  :artist: Drake
- :title: FloRida & Christina Aguilera - Good Feeling ( Acapella Remix )
  :artist: FloRida & Christina Aguilera - Good Feeling ( Acapella Remix )
- :title: Sexy And I Know It
  :artist: LMFAO
- :title: POWER (Album Version (Edited))
  :artist: Kanye West
Eclectic Acquiescence:
- :title: I'd Like To Check You For Ticks
  :artist: Brad Paisley
- :title: Tomorrow Never Comes
  :artist: VNV Nation
- :title: Sleipnir
  :artist: Manowar
- :title: Somebody More Like You
  :artist: Nickel Creek
- :title: Homeless
  :artist: Ed Sheeran
- :title: Undone in Sorrow
  :artist: Crooked Still
- :title: Northwest Passage
  :artist: Stan Rogers
- :title: Learning the ropes
  :artist: Ludique
- :title: A Girl, a Boy, and a Graveyard
  :artist: Jeremy Messersmith
Something Sorta Sentimental Right Now:
- :title: 04. Love You Like a Love Song
  :artist: ! 'Selena Gomez  '
- :title: 06. Memory Lane
  :artist: Elliott Smith
- :title: 02. Every Single Night
  :artist: Fiona Apple
- :title: 01. Some Nights
  :artist: Fun.
- :title: 03. The Purple Bottle
  :artist: Animal Collective
- :title: ! '09. Old Cape Cod '
  :artist: Patti Page
- :title: 05. Try a Little Tenderness / (I Love You) For Sentimental Reasons / You
    Send Me (Live)
  :artist: Sam Cooke
- :title: 07. Hot Knife
  :artist: Fiona Apple
- :title: 08. One Man Guy
  :artist: Loudon Wainwright III
Get Off My Lawn:
- :title: Once and Never Again
  :artist: The Long Blondes
- :title: Unless It's Kicks
  :artist: Okkervil River
- :title: Not Just a "Plus One" On the Guest List
  :artist: Jonathan Richman
- :title: The Twist
  :artist: Frightened Rabbit
- :title: Debaser
  :artist: Pixies
- :title: Vaxxine
  :artist: Visqueen
- :title: Alibi
  :artist: The Mountain Goats
- :title: Andrew in Drag
  :artist: The Magnetic Fields
- :title: Ask
  :artist: The Smiths
- :title: No Culture Icons
  :artist: The Thermals
Fluctuations:
- :title: Obfuse
  :artist: Floating Points
- :title: Tiraquon's Return (A New Home)
  :artist: Space Dimension Controller
- :title: Peepsie
  :artist: Dntel
- :title: Superfrüstück
  :artist: Thomas Fehlman
- :title: Across the Nation
  :artist: Cobblestone Jazz
- :title: Televised Green Smoke
  :artist: Carl Craig
Blame It On My ADD:
- :title: Origins
  :artist: Tennis
- :title: Heartbeats
  :artist: Knife
- :title: Heartbeats
  :artist: José González
- :title: Love Your Friends, Die Laughing
  :artist: Man Overboard
- :title: Tongue Tied
  :artist: Grouplove
- :title: Stop, Drop, Roll
  :artist: Can't Stop Won't Stop
- :title: Lisztomania
  :artist: Phoenix
- :title: Pumped Up Kicks
  :artist: Foster The People
- :title: Gigantic
  :artist: The Pixies
- :title: Sail
  :artist: AWOLNATION
- :title: Man In A Suitcase
  :artist: The Police
Tixmape:
- :title: Ghost Under Rocks
  :artist: Ra Ra Riot
- :title: Almost Crimes (Radio Kills Remix)
  :artist: Broken Social Scene
- :title: Vision One
  :artist: Röyksopp
- :title: time machine
  :artist: LITE
- :title: Lost Kitten
  :artist: Metric
- :title: The End of Medicine
  :artist: The New Pornographers
- :title: A Better Son/Daughter
  :artist: Rilo Kiley
- :title: Young Blood
  :artist: The Naked and Famous
- :title: A Heavy Abacus
  :artist: The Joy Formidable
- :title: Boy Toy
  :artist: Starfucker
tapes:
- :title: Who Will Survive In America
  :artist: Kanye West
What Does Webster Say About Soul:
- :title: Who Will Survive In America
  :artist: Kanye West
- :title: MLK
  :artist: This American Life
- :title: Songs from "Friday Afternoons", Op.7 - Cuckoo!
  :artist: Downside School, Purley, Choir Of
- :title: Hand Covers Bruise, Reprise
  :artist: Trent Reznor and Atticus Ross
- :title: Interlude (Milo)
  :artist: Modest Mouse
- :title: Time to Pretend
  :artist: MGMT
- :title: It's Time
  :artist: Imagine Dragons
- :title: We Have To Respect Each Other
  :artist: Department Of Eagles
- :title: Kites
  :artist: Geographer
Summer Wind:
- :title: Under My Thumb
  :artist: The Rolling Stones
- :title: MoneyGrabber
  :artist: Fitz & the Tantrums
- :title: Treading Water
  :artist: Alex Clare
- :title: Save Room
  :artist: John Legend
- :title: Love Is Dangerous
  :artist: The Dudes
- :title: You Are the Best Thing
  :artist: Ray LaMontagne
- :title: Summer Wind
  :artist: Frank Sinatra
- :title: In the Summertime
  :artist: Mungo Jerry
- :title: Give Me the Night
  :artist: George Benson
- :title: The Man With the Goodnight Gun
  :artist: The Californian
- :title: Fun, Fun, Fun
  :artist: Pharrell
Vacation Day:
- :title: The House That Heaven Built
  :artist: Japandroids
- :title: All of Me
  :artist: Tanlines
- :title: Make Up Your Mind
  :artist: Here We Go Magic
- :title: What You Know
  :artist: Two Door Cinema Club
- :title: I Woke Up Today
  :artist: Port O'Brien
- :title: Stay Away
  :artist: Charles Bradley & Menahan Street Band
- :title: Miles Davis & the Cool
  :artist: The Gaslight Anthem
- :title: Furr
  :artist: Blitzen Trapper
- :title: Helena Beat
  :artist: Foster the People
Transmission Specialist:
- :title: Not the Same
  :artist: Tanlines
- :title: Welcome Home
  :artist: Radical Face
- :title: Proof
  :artist: I Am Kloot
- :title: Polish Girl
  :artist: Neon Indian
- :title: Little Talks
  :artist: Of Monsters And Men
- :title: Original Sin
  :artist: Geographer
- :title: '1996'
  :artist: The Wombats
- :title: Techno Fan
  :artist: The Wombats
- :title: Kelly
  :artist: Van She
